# Generated by Django 3.2.22 on 2023-10-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_image_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_filter',
        ),
    ]
